import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My cool app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <p>Main tag</p>
      </main>

      <footer className={styles.footer}>
        <p>@irfanalamt</p>
      </footer>
    </div>
  );
}
