import * as React from 'react';
import Head from 'next/head';
import { Box, Container } from '@mui/system';
import { Link, Typography } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h2>This is index</h2>
      <Container maxWidth='sm'>
        <Box sx={{ my: 4 }}>
          <Typography variant='h4' component='h1' gutterBottom>
            Test page
          </Typography>
          <Link href='/about' color='secondary'>
            Go to the about page
          </Link>
        </Box>
      </Container>
    </>
  );
}
