import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const defaultEndpoint = `https://rickandmortyapi.com/api/character/`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
export default function Home({ data }) {
  const { results = [] } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>My awesoeme app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my awesome app</h1>

        <p className={styles.description}>Lets go super dev!</p>

        <ul className={styles.grid}>
          {results.map((result) => {
            const { id, name } = result;
            return (
              <li key={id} className={styles.card}>
                <a href='#'>
                  <h3>{name}</h3>
                </a>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>@irfanalamt</footer>
    </div>
  );
}
