
name: Docker Compose Actions Workflow

on:
 pull_request:
  branches: [ main ]
 workflow_dispatch:

jobs:
  build_pull_request:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and run stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
        
