
name: CI Node

on:
 pull_request:
  branches: [ main ]
 workflow_dispatch:
 
defaults:
 run:
    working-directory: ./backend

jobs:
  test_pull_request:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm run build
          
